<a href="https://colab.research.google.com/github/PaulinaTarkowsk/sql_recap/blob/main/Bag_of_Words_zadanie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

# Załaduj dane z pliku CSV do DataFrame
imdb_reviews = pd.read_csv('https://raw.githubusercontent.com/marcin119a/data/refs/heads/main/imdb_reviews_lemmatized.csv')

In [6]:
imdb_reviews.head(15)

sentiment                                  review_lemmatized
0   positive  titanic long well make tragic adventure love s...
1   negative  say independent effort beyond fact shoot telev...
2   negative  maybe fred sandford use say one across lip rel...
3   positive  film comedy expose I ve always hate dog show c...
4   negative  except acting meryl streep note always I d avo...
5   positive  john voight play title character movie base au...
6   positive  one thing really can not seem forget movie beg...
7   negative  christopher lambert attract movie waste plot h...
8   negative  person think entire forensic scene crime commu...
9   positive  catch minute portion movie turner classic movi...
10  negative  love documentaries andy goldsworthy doc greati...
11  negative  get one absolute bad movie I ve ever see life ...
12  negative  total disgrace truly awful screenplay dialogue...
13  negative  get good portion steven seagal environmental a...
14  negative  say think write spoiler alert reveal use fword...

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
vectorizer = CountVectorizer(max_features = 1000)

In [12]:
review_vectors = vectorizer.fit_transform(imdb_reviews["review_lemmatized"])

In [13]:
X = review_vectors.toarray()
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
import numpy as np
from sklearn.model_selection import train_test_split

In [17]:
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, imdb_reviews['sentiment'], test_size=0.3, random_state=42)

model = LogisticRegression(max_iter = 1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [18]:
y_pred = model.predict(X_test)

In [19]:
from sklearn.metrics import classification_report

print("Raport z metrykami modelu:")
print(classification_report(y_test, y_pred))

Raport z metrykami modelu:
              precision    recall  f1-score   support

    negative       0.84      0.82      0.83      1490
    positive       0.83      0.85      0.84      1510

    accuracy                           0.84      3000
   macro avg       0.84      0.84      0.84      3000
weighted avg       0.84      0.84      0.84      3000

